#!/bin/bash

#sysinfo_page - A script to produce an html file

cat <<- _EOF_
	<html>
	<head> 
		<title>My System Information</title>
	</head>

	<body> 
		<h1>My System Information</h1>
	</body>	
	</html>
_EOF_
